title: Locita Adristi Widyatamaka # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C5603AQEa7xkgNDP-5g/profile-displayphoto-shrink_800_800/0/1640843278399?e=1656547200&v=beta&t=MXeECo7QkSQjPjMXX9DCVDIKeECyQJx6soJOW21Ef5o" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm Cita. I'm an undergraduate student at Development Economics of Universitas Airlangga 
  <br><br>
  I'm also joined a Certified Independent Study Program on Data Warehousing, Analysis, and Visualization for Business Insights
  <br><br>
  <a href="https://www.linkedin.com/in/locita-adristi-widyatamaka/"
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
